sqs:
  send-application-to-print-queue-name: ${SQS_SEND_APPLICATION_TO_PRINT_QUEUE_NAME}

api:
  ero-management:
    url: ${API_ERO_MANAGEMENT_URL}

dynamodb:
  print-details-table-name: ${DYNAMODB_PRINT_DETAILS_TABLE_NAME}