sqs:
  send-application-to-print-queue-name: ${SQS_SEND_APPLICATION_TO_PRINT_QUEUE_NAME}

api:
  ero-management:
    url: ${API_ERO_MANAGEMENT_URL}

dynamodb:
  print-details-table-name: ${DYNAMODB_PRINT_DETAILS_TABLE_NAME}
  scheduler-lock-table-name: ${DYNAMODB_SCHEDULER_LOCKS_TABLE_NAME}

jobs:
  enabled: true
  print-requests:
    name: "BatchPrintRequests"
    cron: "${JOB_PRINT_REQUESTS_CRON:0 0 */1 * * *}" # every hour by default
#    lock-at-most-for: ${JOBS_PRINT_REQUEST_LOCK_AT_MOST_FOR}
#    lock-at-least-for: ${JOBS_PRINT_REQUEST_LOCK_AT_LEAST_FOR}
    batchSize: ${JOB_PRINT_REQUESTS_BATCH_SIZE}

thread-pool:
  zip:
    core-size: 5
    max-size: 5
