sqs:
  send-application-to-print-queue-name: ${SQS_SEND_APPLICATION_TO_PRINT_QUEUE_NAME}
  process-print-request-batch-queue-name: ${SQS_PROCESS_PRINT_REQUEST_BATCH_QUEUE_NAME}

api:
  ero-management:
    url: ${API_ERO_MANAGEMENT_URL}

sftp:
  host: ${SFTP_HOST}
  user: ${SFTP_USER}
  password: ${SFTP_PASSWORD}
  private-key: ${SFTP_PRIVATE_KEY}
  print-request-upload-directory: ${SFTP_PRINT_REQUEST_UPLOAD_DIRECTORY}
  print-response-download-directory: ${SFTP_PRINT_RESPONSE_DOWNLOAD_DIRECTORY}

dynamodb:
  print-details-table-name: ${DYNAMODB_PRINT_DETAILS_TABLE_NAME}
  scheduler-lock-table-name: ${DYNAMODB_SCHEDULER_LOCKS_TABLE_NAME}

jobs:
  enabled: true
  lock-at-most-for: "PT10M"
  batch-print-requests:
    name: "BatchPrintRequests"
    cron: "0 0 */1 * * *" # every hour by default
    batch-size: 100
  process-print-responses:
    name: "ProcessPrintResponses"
    cron: "0 0 */1 * * *" # every hour by default

thread-pool:
  zip:
    core-size: 5
    max-size: 5

logging:
  level:
    com:
      jcraft:
        jsch: WARN
